### ISSUE TITLE
GetPlayers() + GetPlayerIDs() Not Working

### ISSUE THREAD

**Issue by alicepolice** [zMoooooritz/go-let-loose#1] opened 2024-08-30 11:48 UTC
[rcon_player_cmd.go](https://github.com/zMoooooritz/go-let-loose/blob/master/pkg/rcon/rcon_player_cmd.go)

GetPlayers() + GetPlayerIDs() 

Not Working

**Comment by zMoooooritz** [comment] 2024-09-03 22:59
Thanks for the report, this is indeed an oversight in the implementation (caused by the inconsistent naming of the hll api)

This will be resolved in the next release that is to come in the next days

**Closed** 2024-09-04 12:38 UTC
